---
title: "insect pred"
author: "Maiga"
date: "30/10/2019"
output:
  html_document:
    keep_md: yes
  pdf_document: default
---
#packages
```{r}
library(tidyverse)
library(caret)
library(ggplot2)
library(e1071)
```

#data
```{r}
insectSize = readr::read_tsv("https://raw.githubusercontent.com/shchurch/insect_egg_database_viz/master/data/dataviz_egg_database.csv")

head (insectSize)
```

#Columns selection
```{r}
insectSizeGroup =insectSize %>% 
  select(logX1,logX2, logvol, group)
```

#missing values

```{r}
length(which(!complete.cases(insectSizeGroup)))
```
#Proportion
```{r}
table(insectSizeGroup$group)
```

# No NA

```{r}
insectSizeClean <- na.omit(insectSizeGroup)
length(which(!complete.cases(insectSizeClean)))

head(insectSizeClean)
```


#Normalization
```{r}
scale2 <- function(x) (x - mean(x, na.rm = TRUE)) / sd(x, TRUE)
insectSizeMeans <- insectSizeClean %>% 
                          mutate_if(is.double, scale2)
head(insectSizeMeans)
```

#Trainnin Set
```{r}
insectSizeTrain <- insectSizeMeans %>%
                  select("logX1",'logX2', "logvol")


head(insectSizeTrain)

insectSizeLabels <- insectSizeMeans$group
```

#Model
```{r}
k <- data.frame(k = 5)
model_knn <- train(x = data.frame(insectSizeTrain),
                   y = insectSizeLabels,
                   method='knn',
                   tuneGrid = k)
head(model_knn)
```
#Prediction
```{r}
newObs <- data.frame(logX1= 0.577,logX2=0.267, logvol= 0.398)

predict(object = model_knn, newdata = newObs)
```

#Visualization

```{r}
new_logX1 <- seq(from = min(insectSizeTrain$logX1), to = max(insectSizeTrain$logX1), length.out = 10)
new_logX2 <- seq(from = min(insectSizeTrain$logX2), to = max(insectSizeTrain$logX2), length.out = 10)
new_logvol <- seq(from = min(insectSizeTrain$logvol), to = median(insectSizeTrain$logvol), length.out = 10)

grid_data <- expand_grid(logX1 = new_logX1,
                         logX2 = new_logX2,
                         logvol = new_logvol)

grid_data$group <- predict(object = model_knn, newdata = as.data.frame(grid_data))

insectSizeMeans %>% 
  ggplot(aes(x = logX1, y = logvol, color = group, fill = group)) + 
  #geom_point(data = grid_data, alpha = 0.5)+ 
  geom_point(alpha = 0.7, pch = 21, color = "black")+ 
  scale_color_brewer(type = "qual")
  #scale_fill_brewer(type = "qual")

```

# Data partition
```{r}
set.seed(500) # makes the random selection of rows reproducible
train <- insectSizeMeans$group %>%
          createDataPartition(p = 0.70, list = FALSE)
head(train)

insectSizeTrain2 <- insectSizeMeans[train,]%>%
                        select("logX1",'logX2', "logvol")
insectSizeTrainTest2 <- insectSizeMeans[-train,]%>%
                          select("logX1",'logX2', "logvol")

insectSizeLabels2 <- insectSizeMeans[train,]$group
                        #select('group')

head(insectSizeLabels2)
typeof(insectSizeLabels2)
```
#Model from partition
```{r}
k <- data.frame(k =5)
model_knn2 <- train(x = data.frame(insectSizeTrain2),
                   y = insectSizeLabels2,
                   method='knn',
                   tuneGrid = k)
head(model_knn2)
```
#Test samples
```{r}
prediction = predict(object = model_knn2, newdata = insectSizeTrainTest2)
prediction


```

#insectSizeMeans into numeric
```{r}

# Convert character vector to factor
comp = insectSizeMeans[-train,]$group 
        #%>%
       #select('group')
tableCompare<- factor(comp, levels = as.character(unique(comp)))

typeof(comp)
head(tableCompare)
```



#ConfusionMatrix

```{r}
confusionMatrix(prediction,tableCompare)


```

#Cross validation
```{r}
trainCross = trainControl(method = 'repeatedcv',
                          number = 10,
                          repeats = 1,
                          search='grid')

#tuneGrid
k <- data.frame(k =3:10)
model_knnVal <- train(x = data.frame(insectSizeTrain2),
                   y = insectSizeLabels2,
                   method='knn',
                   tuneGrid = k,
                   trControl = trainCross)
head(model_knnVal)
```
#Use K=8 for training

```{r}
k <- data.frame(k =8)
model_knn3 <- train(x = data.frame(insectSizeTrain2),
                   y = insectSizeLabels2,
                   method='knn',
                   tuneGrid = k)
head(model_knn3)
```
#Test with K=8
```{r}
prediction2 = predict(object = model_knn3, newdata = insectSizeTrainTest2)
prediction2

```
#Confusion matrix from model K=8
```{r}
confusionMatrix(prediction2,tableCompare)
```

